version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: test_database
    ports:
      - "3306:3306"
  
  backend:
    build: ./test-flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
  
  frontend:
    build: ./test-react-app
    ports:
      - "80:80"
    depends_on:
      - backend