services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_ROOT_PASSWORD: Password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  backend:
    build: ./test-flask-app
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=Password123
      - DB_HOST=db
      - DB_NAME=test_database
    depends_on: 
      - db
  
  frontend:
    build: ./test-react-app
    ports:
      - "80:80"
    depends_on:
      - backend